spring:
  application:
    name: bank_rest

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank_rest}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: false

server:
  port: 8080

app:
  encryption:
    key: ${ENCRYPTION_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

end:
  point:
    id: /{id}

    auth: /api/auth
    register: /register
    login: /login

    cards: /api/cards
    block: /{id}/block

    transfers: /api/transfers

    users: /api/users
    assign:
      role: /{id}/roles

