apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-rest-config
  namespace: nak-rest
data:
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/bank_rest"
  DATABASE_USER: "postgres"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"

  SPRING_PROFILES_ACTIVE: "default"

  ACCESS_TOKEN_EXPIRATION: "900000"
  REFRESH_TOKEN_EXPIRATION: "604800000"